# From the famous Cobalt2 sublime theme
# Source  https//github.com/wesbos/cobalt2/tree/master/Cobalt2

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 10
unfocused_hollow = true
thickness = 0.2


