# From the famous Cobalt2 sublime theme
# Source  https//github.com/wesbos/cobalt2/tree/master/Cobalt2

# Default colors
[colors.primary]
background = '#122637'
foreground = '#ffffff'

[colors.cursor]
text = '#122637'
cursor = '#47ff9c'

