[env]
TERM = "xterm-256color"

[window]

#opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "MesloLGS NERD FONT"
bold.family = "MesloLGS NERD FONT"
#normal.family = "JetBrains Nerd Font"
#bold.family = "JetBrains Nerd Font"
italic.family = "MesloLGS NERD FONT"
bold_italic.family = "MesloLGS NERD FONT"

size = 14.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.

[general]
    import = [
        "~/.config/alacritty/themes/mytheme.toml",
    ]

